parameters:
    database_driver:    pdo_mysql
    database_host:      127.0.0.1
    database_port:      null
    database_name:      pfc
    database_user:      a
    database_password:  aa
    mailer_transport:   smtp
    mailer_host:        127.0.0.1
    mailer_user:        null
    mailer_password:    null
    locale:             es
    secret:             a4ea89d5ba977c385318f28e23739444
    database_path:      null
