security:
    firewalls:
#        firewall_1:
#            # ...
#            http_basic:
#                provider:  nombre-del-proveedor
#        
#        firewall_2:
#            # ...
#            http_digest:
#                provider:  nombre-del-proveedor
#        
#        firewall_3:
#            # ...
#            x509:
#                provider:  nombre-del-proveedor
#        
        firewall_4:
            pattern:     ^/*
            anonymous:   ~
#            http_basic:
#                realm: "Area Segura"            
#            form_login:  ~
            form_login:  
                login_path: usuario_login
                check_path: usuario_login_check 
            remember_me:
                key:      "%secret%"
#                name:     NameOfTheCookie
                lifetime: 10
#            default_target_path: /sobre
#            always_use_default_target_path:  true   
#            logout:  ~    
            logout:
                path:   usuario_logout
                target: /   
             #ROLE_ALLOWED_TO_SWITCH
#            switch_user: true                
#            switch_user: { role: ROLE_USUARIO }                
    
    access_control:
        - { path: ^/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/perfil,   roles: ROLE_USUARIO }
#        - { path: ^/activar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
     
    providers:
        chain_provider:
            chain:
                providers: [user_db]
#                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
#                    foo: { password: test , roles: 'ROLE_USUARIO' }
                    - { name: x ,  password: x , roles: 'ROLE_USUARIO' }
        user_db:
            entity: { class: pfc\InicioBundle\Entity\Usuario, property: email }      
    
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
#        pfc\InicioBundle\Entity\Usuario: plaintext
        pfc\InicioBundle\Entity\Usuario: { algorithm: sha512, iterations: 1 }               
            
#jms_security_extra:
#    secure_all_services: false
#    expressions: true
#
#security:
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
#
#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
#
#    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
#
#    firewalls:
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        login:
#            pattern:  ^/demo/secured/login$
#            security: false
#
#        secured_area:
#            pattern:    ^/demo/secured/
#            form_login:
#                check_path: _security_check
#                login_path: _demo_login
#            logout:
#                path:   _demo_logout
#                target: _demo
#            #anonymous: ~
#            #http_basic:
#            #    realm: "Secured Demo Area"
#
#    access_control:
#        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
