#pendi:borrar   

proves:
    pattern:      /p/{pag}
    defaults:     { _controller: "InicioBundle:Default:index" , pag:index}
    
viajeOO:
    pattern:      /viajeOO
    defaults:     { _controller: "InicioBundle:Default:viajeOO" }      
    requirements: { _method: post|get }    