<?php

namespace pfc\InicioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
    public function findUsuarioRegistrado($id,$fechaBaja,$password)
    {
        $em = $this->getEntityManager();
 
        $consulta = $em->createQuery('
            SELECT u
              FROM InicioBundle:Usuario u
             WHERE u.id         = :id
               AND u.fechaBaja = :fechaBaja
               AND u.password   = :password
          ');
        $consulta->setParameter('id'        ,$id)
                 ->setParameter('fechaBaja' ,$fechaBaja)
                 ->setParameter('password'  ,$password)
                ;
 
        return $consulta->getResult();
    }    
}
