<?php

namespace pfc\InicioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ViajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViajeRepository extends EntityRepository
{
}
