portada:
    pattern:    /
    defaults:   { _controller: "InicioBundle:Sitio:portada" }       
    
pagina_estatica:
    pattern:    /sitio/{pagina}
    defaults:   { _controller: "InicioBundle:Sitio:estatica" }
    
# soluciona el trailing slash problem    
_pagina_estatica:
    pattern:    /sitio/{pagina}/
    defaults: 
        _controller:  FrameworkBundle:Redirect:redirect
        route:        pagina_estatica
        permanent:    true
    
contacto:
    pattern:    /contacto
    defaults:   { _controller: "InicioBundle:Sitio:contacto" }
    requirements:
        _method:  GET|POST
        
usuario_registro:
    pattern:    /registro/{codigo}
    defaults:   { _controller: "InicioBundle:Sitio:registro" , codigo:null}    
    
usuario_login:
    pattern:    /login
    defaults:   { _controller: "InicioBundle:Sitio:login" }

usuario_login_check:
    pattern:    /login_check

usuario_logout:
    pattern:    /logout  
    
usuario_perfil:
    pattern:    /perfil
    defaults:   { _controller: "InicioBundle:Sitio:perfil" }         
    
InicioBundle_viaje:
    resource:   "@InicioBundle/Resources/config/routing/viaje.yml"
    prefix:     /viaje    
    
#pendi:borrar       
InicioBundle_proves:
    resource:   "@InicioBundle/Resources/config/routing/proves.yml"