inicio_hola:
    pattern:  /hola/{name}
    defaults: { _controller: InicioBundle:Default:index }
    
pagina_estatica:
    pattern:  /sitio/{pagina}
    defaults: { _controller: InicioBundle:Sitio:estatica }
    
# soluciona el trailing slash problem    
_pagina_estatica:
    pattern:  /sitio/{pagina}/
    defaults: 
        _controller:  FrameworkBundle:Redirect:redirect
        route:        pagina_estatica
        permanent:    true

contacto:
    pattern:  /contacto
    defaults: { _controller: InicioBundle:Sitio:contacto }
    requirements:
        _method:  GET|POST
        
portada:
    pattern:  /
    defaults: { _controller: InicioBundle:Default:portada }       
    
#A partir de Symfony 2.1, debes tener configuradas las direcciones URL para las 3 rutas    
usuario_login:
    pattern:   /login
    defaults:  { _controller: InicioBundle:Sitio:login }

usuario_login_check:
    pattern:   /login_check

usuario_logout:
    pattern:   /logout  
    
        
usuario_perfil:
    pattern:  /perfil
    defaults: { _controller: InicioBundle:Sitio:perfil }         
    
usuario_registro:
    pattern:  /registro
    defaults: { _controller: InicioBundle:Sitio:registro }    