proves:
    pattern:    /p/{pag}
    defaults:   { _controller: InicioBundle:Default:index , pag:index}
    
pagina_estatica:
    pattern:    /sitio/{pagina}
    defaults:   { _controller: InicioBundle:Sitio:estatica }
    
# soluciona el trailing slash problem    
_pagina_estatica:
    pattern:    /sitio/{pagina}/
    defaults: 
        _controller:  FrameworkBundle:Redirect:redirect
        route:        pagina_estatica
        permanent:    true
    
contacto:
    pattern:    /contacto
    defaults: { _controller: InicioBundle:Sitio:contacto }
    requirements:
        _method:  GET|POST
        
usuario_registro:
    pattern:    /registro/{codigo}
    defaults:   { _controller: InicioBundle:Sitio:registro , codigo:null}    
    
usuario_login:
    pattern:    /login
    defaults:   { _controller: InicioBundle:Sitio:login }

usuario_login_check:
    pattern:    /login_check

usuario_logout:
    pattern:    /logout  
    
        
usuario_perfil:
    pattern:    /perfil
    defaults:   { _controller: InicioBundle:Sitio:perfil }         
#pendi:borrar    
usuario_perfilx:
    pattern:    /perfilx
    defaults:   { _controller: InicioBundle:Sitio:perfilx }         
    
portada:
    pattern:    /
    defaults:   { _controller: InicioBundle:Sitio:portada }       
    
extranet_portada:
    pattern:    /extranet
    defaults:   { _controller: InicioBundle:Extranet:portada }    