parameters:
#    inicio.example.class: pfc\InicioBundle\Example

services:
#    kernel.listener.login_listener:
    login_listener:
        class: pfc\InicioBundle\Listener\LoginListener
#        arguments: [@doctrine]
        arguments: [@security.context, @doctrine, @session]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
#           - { name: kernel.event_listener, event: kernel.response }   