parameters:
#    inicio.example.class: pfc\InicioBundle\Example

services:
    login_listener:
        class:      pfc\InicioBundle\Listener\LoginListener
        arguments:  [@doctrine]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login , method: onSecurityInteractiveLogin}